version: '2.0'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:

#---------------------------------------------------------------------------#
# CogStack containers                                                       #
#---------------------------------------------------------------------------#
  cogstack:
    volumes:
      - ./cogstack/test2.sh:/cogstack/test2.sh:ro

#---------------------------------------------------------------------------#
# Postgres container for input data                                         #
#---------------------------------------------------------------------------#
  pgsamples:
    ports:
      # <host:container> expose the postgres DB to host for debugging purposes
      - "5555:5432"

#---------------------------------------------------------------------------#
# Elasticsearch cluster                                                     #
#---------------------------------------------------------------------------#
  elasticsearch:
    ports:
      - "9200:9200"

#---------------------------------------------------------------------------#
# Kibana webapp                                                             #
#---------------------------------------------------------------------------#
  kibana:
    ports:
      - "5601:5601"
