version: '2.0'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:

#---------------------------------------------------------------------------#
# Postgres container with input data                                        #
#---------------------------------------------------------------------------#
  samples-db:
    ports:
      # <host:container> expose the postgres DB to host for debugging purposes
      - "5555:5432"

#---------------------------------------------------------------------------#
# CogStack-Pipeline related containers                                      #
#---------------------------------------------------------------------------#
  cogstack-pipeline:
    volumes:
      - ./cogstack/conf:/cogstack/cogstack_conf:ro
      - ./cogstack/run_pipeline.sh:/cogstack/run_pipeline.sh:ro

#---------------------------------------------------------------------------#
# Elasticsearch cluster                                                     #
#---------------------------------------------------------------------------#
  elasticsearch-1:
    ports:
      - "9200:9200"

#---------------------------------------------------------------------------#
# Kibana webapp                                                             #
#---------------------------------------------------------------------------#
  kibana:
    ports:
      - "5601:5601"
