version: '2.0'
services:


  postgres:
    image: cogstacksystems/postgres:latest
    ports:
      - 5432:5432
    networks:
      - esnet


  cogstack:
    image: cogstacksystems/cogstack-pipeline:latest
    environment:
      - LOG_LEVEL=info
      - FILE_LOG_LEVEL=off
    depends_on:
      - postgres
      - elasticsearch3
    networks:
      - esnet


  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=['elasticsearch1', 'elasticsearch2', 'elasticsearch3']"
    depends_on:
      - postgres
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet


  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=['elasticsearch1', 'elasticsearch2', 'elasticsearch3']"
    depends_on:
      - elasticsearch1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet


  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=['elasticsearch1', 'elasticsearch2', 'elasticsearch3']"
    depends_on:
      - elasticsearch2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - esnet


  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch3
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro 
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local  


networks:
  esnet:
    driver: bridge
