version: '2.0'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:

#---------------------------------------------------------------------------#
# Postgres container for input data                                         #
#---------------------------------------------------------------------------#
  samples-db:
    ports:
      # <host:container> expose the postgres DB to host for debugging purposes
      - "5555:5432"
    networks:
      - esnet
      - public

#---------------------------------------------------------------------------#
# CogStack-Pipeline related containers                                      #
#---------------------------------------------------------------------------#
  cogstack-pipeline:
    networks:
      - esnet

  cogstack-job-repo:
    networks:
      - esnet

#---------------------------------------------------------------------------#
# Elasticsearch cluster                                                     #
#---------------------------------------------------------------------------#
  elasticsearch-1:
    ports:
      - 9200
    networks:
      - esnet

#---------------------------------------------------------------------------#
# Kibana webapp                                                             #
#---------------------------------------------------------------------------#
  kibana:
    networks:
      - esnet

#---------------------------------------------------------------------------#
# Reverse proxy (+ host-container proxy and basic auth)                     #
#---------------------------------------------------------------------------#
  nginx-proxy:
    image: nginx:1.13.1-alpine
    restart: always
    networks:
      - public
      - esnet
    depends_on:
      - kibana
      - elasticsearch-1
    ports:
      - "5601:5601"
      - "9200:9200"
    volumes:
      - ./common/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./common/nginx/auth/.htpasswd:/etc/apache2/.htpasswd:ro


#---------------------------------------------------------------------------#
# Docker virtual networks                                                   #
#---------------------------------------------------------------------------#
networks:
  esnet:
    driver: bridge
  public:
    driver: bridge
