version: '2.0'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:

#---------------------------------------------------------------------------#
# CogStack containers                                                       #
#---------------------------------------------------------------------------#
  cogstack:
    image: cogstacksystems/cogstack-pipeline-gate:dev-latest
    volumes:
      - ./cogstack:/usr/src/docker-cogstack/cogstack/cogstack_conf:ro
      - ./gate/app:/gate/app
