#---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml

#----------------------
# single node cluster conf
#----------------------
## Use single node discovery in orhttps
discovery.type: single-node

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
# discovery.zen.minimum_master_nodes: 1

#----------------------
# multi node cluster conf
#----------------------
cluster.name: "cogstack-elastic-cluster"
network.host: 0.0.0.0
discovery.seed_hosts: ["0.0.0.0"]
http.port: 9200
transport.host: 0.0.0.0
#discovery.zen.ping.unicast.hosts: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
# discovery.zen.minimum_master_nodes: -1

#----------------------
# X-Pack features
# disabled by default when using '-oss' images
# need to be disabled manually when using standard images from elastic
#----------------------
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.security.http.ssl.enabled: false
xpack.security.authc.api_key.enabled : true
xpack.security.authc.api_key.cache.ttl : 1d
xpack.security.authc.api_key.cache.max_keys : 20000
xpack.security.authc.api_key.cache.hash_algo : ssha256

#xpack.graph.enabled: false
#xpack.ml.enabled: false
#xpack.monitoring.enabled: false
#xpack.reporting.enabled: false
#xpack.watcher.enabled: false


######## Start OpenDistro for Elasticsearch Security Demo Configuration ########
# WARNING: revise all the lines below before you go into production
# opendistro_security.ssl.transport.pemcert_filepath: esnode.pem
# opendistro_security.ssl.transport.pemkey_filepath: esnode.key
# opendistro_security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
# opendistro_security.ssl.transport.enforce_hostname_verification: false
# opendistro_security.ssl.http.enabled: true
# opendistro_security.ssl.transport.enabled=false
# 
# opendistro_security.ssl.http.pemcert_filepath: esnode.pem
# opendistro_security.ssl.http.pemkey_filepath: esnode.key
# opendistro_security.ssl.http.pemtrustedcas_filepath: root-ca.pem
# #opendistro_security.allow_unsafe_democertificates: true
# opendistro_security.allow_default_init_securityindex: true
# opendistro_security.authcz.admin_dn:
# #  - CN=kirk,OU=client,O=client,L=test, C=de
#   - 'CN=cogstack' 
# 
# opendistro_security.nodes_dn:
#   - 'CN=elasticsearch-*'
# 
# opendistro_security.audit.type: internal_elasticsearch
# opendistro_security.enable_snapshot_restore_privilege: true
# opendistro_security.check_snapshot_restore_write_privileges: true
# opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
# cluster.routing.allocation.disk.threshold_enabled: false
# node.max_local_storage_nodes: 3
######## End OpenDistro for Elasticsearch Security Demo Configuration ########
