version: '2'

services:

  postgres:
    build: ../../../../test/dockerfiles/postgres
    command: "-c 'shared_buffers=256MB' -c 'max_connections=1000'"
    ports:
      - 5432:5432
    networks:
      - esnet

  sqlserver:
    build: ../../../../test/dockerfiles/sqlserver
      #image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      - "ACCEPT_EULA=y"
      - "SA_PASSWORD=yourStrong(!)Password"
    ports:
      - 1433:1433
    networks:
      - esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
#      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
      - http.publish_port=9300
      - transport.host=localhost
      - transport.tcp.port=9300
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

#  kibana:
#    image: docker.elastic.co/kibana/kibana-oss:6.4.2
#    environment:
#        ELASTICSEARCH_URL: http://elasticsearch:9200
#    ports:
#      - 5601:5601
#    networks:
#      - esnet

# disabling Bio-Yodie due to UMLS license issues
#  bioyodie:
#      build: ../../../../docker-cogstack/bioyodie
#      cpu_quota: 800000
#      image: cogstacksystems/bioyodie:D4.5
#      ports:
#        - 8080:8080
#      restart: on-failure
#      networks:
#        - esnet


networks:
  esnet:
    driver: bridge
