source:
  es:
    hosts: ["http://elastic:admin@127.0.0.1:9200"]
    index-name: 'sample_observations_view'
    #security:
    #  ca-certs-path: "/app/config/root-ca.pem"
    #  client-cert-path: "/app/config/client.pem"
    #  client-key-path: "/app/config/client.key"

sink:
  es:
    hosts: ["http://elastic:admin@127.0.0.1:9200"]
    index-name: 'sample_observations_view_annotations'
    #security:
    #  ca-certs-path: "/app/config/root-ca.pem"
    #  client-cert-path: "/app/config/client.pem"
    #  client-key-path: "/app/config/client.key"

nlp-service:
  endpoint-url: 'http://127.0.0.1:5000/api/process'

mapping:
  source:
    text-field: 'encounter_document'
    docid-field: 'encounter_id'
    persist-fields:
      - 'encounter_id'
    #  - 'patient_id'
    #  - 'encounter_start'
    #  - 'encounter_end'
    batch:
      date-field: 'encounter_start'
      date-format: 'yyyy-MM-dd'
      python-date-format: '%Y-%m-%d' 
      interval: 30 
      date-start: '1922-01-01'
      date-end: '2099-06-01'
      threads: 8
  sink:
    split-index-by-field: ''
  nlp:
    skip-processed-doc-check: 'true'
    annotation-id-field: 'id'
