version: '2'
services:
  postgres:
    build: ../../postgres
    image: cogstack.systems/postgres
    ports:
      - 5432:5432
    networks:
      - esnet
  cogstack:
    build: ../../../
    image: cogstack.systems/cogstack:1.2.0
    environment:
      - LOG_LEVEL=info
      - FILE_LOG_LEVEL=off
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.2
    environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
      - http.publish_port=9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
