ARG VERSION

FROM cogstacksystems/cogstack-java-run:${VERSION}

# setup the build environment
#
RUN mkdir -p /devel
WORKDIR /devel

COPY ./gradle/wrapper /devel/gradle/wrapper
COPY ./gradlew /devel/

RUN ./gradlew --version

COPY ./build.gradle ./settings.gradle /devel/
COPY . /devel/


# build cogstack
RUN ./gradlew bootRepackage

#CMD ./gradlew bootRepackage
