version: '2.0'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:

#---------------------------------------------------------------------------#
# Postgres container for input data                                         #
#---------------------------------------------------------------------------#
  pgsamples:
    image: postgres:11.1-alpine
    volumes:
      - ./db_dump:/data/:ro
      - ./common/pgsamples/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
      - pgsamdata:/var/lib/postgresql/data
# TODO: fix POSTGRES password management                                    #
#    environment:
#      - "POSTGRES_PASSWORD=postgresadminpass"
# pgsamples will be usually available at this port
#    ports:
      # <host:container> expose the postgres DB to host for debugging purposes
#      - "5555:5432"

#---------------------------------------------------------------------------#
# Postgres container for spring batch / cogstack testing                    #
#---------------------------------------------------------------------------#
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - ./common/postgres/create_repo.sh:/docker-entrypoint-initdb.d/create_repo.sh:ro
      - pgdata:/var/lib/postgresql/data
# TODO: fix POSTGRES password management
#    environment:
#      - "POSTGRES_PASSWORD=postgresadminpass"
    ports:
      - 5432

#---------------------------------------------------------------------------#
# CogStack containers                                                       #
#---------------------------------------------------------------------------#
  cogstack:
    image: cogstacksystems/cogstack-pipeline:dev-latest
#    image: cogstacksystems/cogstack-pipeline:local
    volumes:
      - ./cogstack:/cogstack/job_config:ro
    environment:
      - LOG_LEVEL=info
      - FILE_LOG_LEVEL=off
      - LOG_FILE_NAME=cogstack_job_log
    depends_on:
      - pgsamples
      - postgres
      - elasticsearch
    command: ./run_pipeline.sh /cogstack/cogstack-*.jar /cogstack/job_config

#---------------------------------------------------------------------------#
# Elasticsearch cluster                                                     #
#---------------------------------------------------------------------------#
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - postgres
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./common/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
# elastic will be usually available at this port
#    ports:
#      - "9200:9200"

#---------------------------------------------------------------------------#
# Kibana webapp                                                             #
#---------------------------------------------------------------------------#
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    depends_on:
      - elasticsearch
    volumes:
      - ./common/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
# kibana will be usually available at this port
#    ports:
#      - "5601:5601"


#---------------------------------------------------------------------------#
# Docker named volumes                                                      #
#---------------------------------------------------------------------------#
volumes:
  esdata1:
    driver: local
  pgsamdata:
    driver: local
  pgdata:
    driver: local
