## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
#elasticsearch.url: http://elasticsearch-1:9200


# --------
# X-Pack features
# disabled by default when using '-oss' images
# need to be disabled manually when using standard images from elastic
# --------
#xpack.security.enabled: false
#xpack.graph.enabled: false
#xpack.ml.enabled: false
#xpack.monitoring.enabled: false
#xpack.reporting.enabled: false
#xpack.watcher.enabled: false
