version: '2.0'

#---------------------------------------------------------------------------#
# Used services                                                             #
#                                                                           #
# Since we use 2 data sources with different dependencies                   #
# it's easier here not to use services configuration override file          #
#---------------------------------------------------------------------------#
services:

#---------------------------------------------------------------------------#
# Postgres containers for input data                                        #
#---------------------------------------------------------------------------#
  pgsamples:
    ports:
      # <host:container> expose the postgres DB to host for debugging purposes
      - "5555:5432"

  pgmtsamples:
    image: postgres:10.4-alpine
    volumes:
      - ./db_dump/db_samples-mt.sql.gz:/data/db_samples.sql.gz:ro
      - ./common/pgsamples/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
      - pgmtdata:/var/lib/postgresql/data
    ports:
      - "5556:5432"

#---------------------------------------------------------------------------#
# Postgres container for spring batch / cogstack testing                    #
# TODO: fix password management
#---------------------------------------------------------------------------#
  postgres:
    ports:
      - 5432

#---------------------------------------------------------------------------#
# CogStack containers                                                       #
#---------------------------------------------------------------------------#
  cogstack:
    depends_on:
      - pgmtsamples

#---------------------------------------------------------------------------#
# Elasticsearch cluster                                                     #
#---------------------------------------------------------------------------#
  elasticsearch:
    ports:
      - "9200:9200"

#---------------------------------------------------------------------------#
# Kibana webapp                                                             #
#---------------------------------------------------------------------------#
  kibana:
    ports:
      - "5601:5601"


#---------------------------------------------------------------------------#
# Docker named volumes                                                      #
#---------------------------------------------------------------------------#
volumes:
  pgmtdata:
    driver: local
