version: '2.0'

#---------------------------------------------------------------------------#
# Used services                                                             #
#                                                                           #
# Since we use 2 data sources with different dependencies                   #
# it's easier here not to use services configuration override file          #
#---------------------------------------------------------------------------#
services:

#---------------------------------------------------------------------------#
# Postgres containers with sample data                                      #
#---------------------------------------------------------------------------#
  samples-db:
    ports:
#       <host:container> expose the postgres DB to host for debugging purposes
      - "5555:5432"

  mtsamples-db:
    image: postgres:11.1-alpine
    volumes:
      - ./db_dump/db_samples-mt.sql.gz:/data/db_samples.sql.gz:ro
      - ./common/pgsamples/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
      - mtsamples-vol:/var/lib/postgresql/data
    ports:
      - "5556:5432"

#---------------------------------------------------------------------------#
# CogStack-Pipeline related containers                                      #
#---------------------------------------------------------------------------#
  cogstack-pipeline:
    environment:
      - SERVICES_USED=cogstack-job-repo:5432,samples-db:5432,mtsamples-db:5432,elasticsearch-1:9200
    depends_on:
      - mtsamples-db

#---------------------------------------------------------------------------#
# Elasticsearch cluster                                                     #
#---------------------------------------------------------------------------#
  elasticsearch-1:
    ports:
      - "9200:9200"

#---------------------------------------------------------------------------#
# Kibana webapp                                                             #
#---------------------------------------------------------------------------#
  kibana:
    ports:
      - "5601:5601"


#---------------------------------------------------------------------------#
# Docker named volumes                                                      #
#---------------------------------------------------------------------------#
volumes:
  mtsamples-vol:
    driver: local
