name: Docker

on:

  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: checkout repo
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: cogstacksystems/cogstack-pipeline:dev-latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context : .
          file : "Dockerfile"
          allow: network.host
          github-token: ${{ github.token }}
          tags: cogstacksystems/cogstack-pipeline:dev-latest
          push : true
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}